Make system-tests fail only on merge to master (#1572)

diff --git a/.drone-github.yml b/.drone-github.yml
--- a/.drone-github.yml
+++ b/.drone-github.yml
@@ -102,9 +102,52 @@ steps:
   - name: systemtests-PR
     image: docker.pkg.github.com/vegaprotocol/system-tests/system-tests:latest
     pull: always
+    environment:
+      GITHUB_API_TOKEN:
+        from_secret: GITHUB_API_TOKEN
+      SLACK_HOOK_URL:
+        from_secret: SLACK_HOOK_URL
     commands:
       # https://github.com/vegaprotocol/system-tests/blob/master/systemtests.sh
-      - /usr/local/bin/systemtests.sh -v all
+      - codefile="$$(mktemp)" ; logfile="$$(mktemp)"
+      - (
+          /usr/local/bin/systemtests.sh -v all ;
+          echo "$$?" >"$$codefile"
+        ) 2>&1 | tee "$$logfile"
+      - code="$$(cat "$$codefile")"
+      - if test "$$code" -gt 0 ; then
+          # system-tests failed
+          msgprefix="system-tests failed for PR#$$DRONE_PULL_REQUEST (\`$$DRONE_SOURCE_BRANCH\` -> \`$$DRONE_TARGET_BRANCH\`)" ;
+          if test "$$DRONE_TARGET_BRANCH" == master ; then
+            # Failure while attempting to merge to master is fatal.
+            exitcode=1 ;
+            msg="$$msgprefix *pipeline failed* :cry:" ;
+          else
+            exitcode=0 ;
+            msg="$$msgprefix (pipeline continues)" ;
+          fi ;
+          # Notify Slack
+          slack-notify.py
+            --hookurl "$$SLACK_HOOK_URL"
+            --recipient "#tradingcore"
+            --text "$$msg"
+            --username "nagbot" ;
+          fi ;
+          (
+            echo "system-tests failed." ;
+            echo ;
+            echo '```' ;
+            grep -A1000 '=== Test summary ===' "$$logfile" ;
+            echo '```'
+          ) >/tmp/comment.txt ;
+          github_issue_comment.py
+            --token "$$GITHUB_API_TOKEN"
+            --owner vegaprotocol
+            --repo vega
+            --issue "$$DRONE_PULL_REQUEST"
+            --comment "$$(cat /tmp/comment.txt)" ;
+          exit "$$exitcode" ;
+        fi
     depends_on:
       - test-PR
     when:
