Disable some CI to speed up testing (#1572)

diff --git a/.drone-github.yml b/.drone-github.yml
--- a/.drone-github.yml
+++ b/.drone-github.yml
@@ -55,49 +55,49 @@ steps:
       event:
         - pull_request
 
-  - name: markdownspellcheck-PR
-    image: docker.pkg.github.com/vegaprotocol/devops-infra/markdownspellcheck:latest
-    pull: always
-    environment: {}
-    commands:
-      # Make sure the mdspell command matches the one in Makefile.
-      - mdspell --en-gb --ignore-acronyms --ignore-numbers --no-suggestions --report '*.md' 'docs/**/*.md'
-    depends_on:
-      - build-PR
-    when:
-      event:
-        - pull_request
+  # - name: markdownspellcheck-PR
+  #   image: docker.pkg.github.com/vegaprotocol/devops-infra/markdownspellcheck:latest
+  #   pull: always
+  #   environment: {}
+  #   commands:
+  #     # Make sure the mdspell command matches the one in Makefile.
+  #     - mdspell --en-gb --ignore-acronyms --ignore-numbers --no-suggestions --report '*.md' 'docs/**/*.md'
+  #   depends_on:
+  #     - build-PR
+  #   when:
+  #     event:
+  #       - pull_request
 
-  - name: test-PR
-    image: docker.pkg.github.com/vegaprotocol/devops-infra/cipipeline:1.11.13
-    volumes:
-      - name: gocache
-        path: /go/cache
-      - name: gopkg
-        path: /go/pkg
-    environment:
-      GOCACHE: /go/cache
-      GITHUB_API_TOKEN:
-        from_secret: GITHUB_API_TOKEN
-      SLACK_HOOK_URL:
-        from_secret: SLACK_HOOK_URL
-    commands:
-      - make retest
-      # More small checks. Run all, instead of exitng after first failure.
-      - failed=""
-      - for target in codeowners_check gqlgen_check print_check proto_check race vet ; do
-          echo "$$COL_CYAN$$target$$COL_RESET" ; make "$$target" || failed="$$failed $$target" ; done
-      - /usr/local/bin/check-rest-endpoints.py
-          --bindings gateway/rest/grpc-rest-bindings.yml
-          --swagger proto/api/trading.swagger.json || failed="$$failed rest_check"
-      - /usr/local/bin/multilint || failed="$$failed multilint"
-      - make staticcheck || true  # Ignore failures until they're all fixed.
-      - if test -n "$$failed" ; then echo "Failed checks:$$failed" ; exit 1 ; fi ; echo "$${COL_GREEN}OK$$COL_RESET"
-    depends_on:
-      - build-PR
-    when:
-      event:
-        - pull_request
+  # - name: test-PR
+  #   image: docker.pkg.github.com/vegaprotocol/devops-infra/cipipeline:1.11.13
+  #   volumes:
+  #     - name: gocache
+  #       path: /go/cache
+  #     - name: gopkg
+  #       path: /go/pkg
+  #   environment:
+  #     GOCACHE: /go/cache
+  #     GITHUB_API_TOKEN:
+  #       from_secret: GITHUB_API_TOKEN
+  #     SLACK_HOOK_URL:
+  #       from_secret: SLACK_HOOK_URL
+  #   commands:
+  #     - make retest
+  #     # More small checks. Run all, instead of exitng after first failure.
+  #     - failed=""
+  #     - for target in codeowners_check gqlgen_check print_check proto_check race vet ; do
+  #         echo "$$COL_CYAN$$target$$COL_RESET" ; make "$$target" || failed="$$failed $$target" ; done
+  #     - /usr/local/bin/check-rest-endpoints.py
+  #         --bindings gateway/rest/grpc-rest-bindings.yml
+  #         --swagger proto/api/trading.swagger.json || failed="$$failed rest_check"
+  #     - /usr/local/bin/multilint || failed="$$failed multilint"
+  #     - make staticcheck || true  # Ignore failures until they're all fixed.
+  #     - if test -n "$$failed" ; then echo "Failed checks:$$failed" ; exit 1 ; fi ; echo "$${COL_GREEN}OK$$COL_RESET"
+  #   depends_on:
+  #     - build-PR
+  #   when:
+  #     event:
+  #       - pull_request
 
   - name: systemtests-PR
     image: docker.pkg.github.com/vegaprotocol/system-tests/system-tests:latest
@@ -149,7 +149,8 @@ steps:
           exit "$$exitcode" ;
         fi
     depends_on:
-      - test-PR
+      - build-PR # !!!!!!!!!!!!!!!!!! DO NOT MERGE !!!!!!!!!!!!!!!!!!!!!!!!!
+      # - test-PR
     when:
       event:
         - pull_request
