Remove tmp changes (#1595)

diff --git a/.drone-github.yml b/.drone-github.yml
--- a/.drone-github.yml
+++ b/.drone-github.yml
@@ -76,77 +76,76 @@ steps:
       SLACK_HOOK_URL:
         from_secret: SLACK_HOOK_URL
     commands:
-      - echo OK
-      # - make retest
-      # # More small checks. Run all, instead of exitng after first failure.
-      # - failed=""
-      # - for target in codeowners_check gqlgen_check print_check proto_check race vet ; do
-      #     echo "$$COL_CYAN$$target$$COL_RESET" ; make "$$target" || failed="$$failed $$target" ; done
-      # - /usr/local/bin/check-rest-endpoints.py
-      #     --bindings gateway/rest/grpc-rest-bindings.yml
-      #     --swagger proto/api/trading.swagger.json || failed="$$failed rest_check"
-      # - /usr/local/bin/multilint || failed="$$failed multilint"
-      # - make staticcheck || true  # Ignore failures until they're all fixed.
-      # - if test -n "$$failed" ; then echo "Failed checks:$$failed" ; exit 1 ; fi ; echo "$${COL_GREEN}OK$$COL_RESET"
+      - make retest
+      # More small checks. Run all, instead of exitng after first failure.
+      - failed=""
+      - for target in codeowners_check gqlgen_check print_check proto_check race vet ; do
+          echo "$$COL_CYAN$$target$$COL_RESET" ; make "$$target" || failed="$$failed $$target" ; done
+      - /usr/local/bin/check-rest-endpoints.py
+          --bindings gateway/rest/grpc-rest-bindings.yml
+          --swagger proto/api/trading.swagger.json || failed="$$failed rest_check"
+      - /usr/local/bin/multilint || failed="$$failed multilint"
+      - make staticcheck || true  # Ignore failures until they're all fixed.
+      - if test -n "$$failed" ; then echo "Failed checks:$$failed" ; exit 1 ; fi ; echo "$${COL_GREEN}OK$$COL_RESET"
     depends_on:
       - build-PR
     when:
       event:
         - pull_request
 
-  # - name: systemtests-PR
-  #   image: docker.pkg.github.com/vegaprotocol/system-tests/system-tests:latest
-  #   pull: always
-  #   environment:
-  #     GITHUB_API_TOKEN:
-  #       from_secret: GITHUB_API_TOKEN
-  #     SLACK_HOOK_URL:
-  #       from_secret: SLACK_HOOK_URL
-  #   commands:
-  #     # https://github.com/vegaprotocol/system-tests/blob/master/systemtests.sh
-  #     - codefile="$$(mktemp)" ; logfile="$$(mktemp)"
-  #     - ln -fs cmd/vega/vega-linux-amd64 cmd/vega/vega
-  #     - (
-  #         /usr/local/bin/systemtests.sh -v all ;
-  #         echo "$$?" >"$$codefile"
-  #       ) 2>&1 | tee "$$logfile"
-  #     - test "$$(cat "$$codefile")" = 0 && exit 0
-  #     # system-tests failed
-  #     - msgprefix="system-tests failed for PR#$$DRONE_PULL_REQUEST (\`$$DRONE_SOURCE_BRANCH\` -> \`$$DRONE_TARGET_BRANCH\`)"
-  #     # Failure is fatal only while attempting to merge to master.
-  #     - if test "$$DRONE_TARGET_BRANCH" = master ; then
-  #         exitcode=1 ;
-  #         msg="$$msgprefix *pipeline failed* :cry:" ;
-  #       else
-  #         exitcode=0 ;
-  #         msg="$$msgprefix (pipeline continues)" ;
-  #       fi
-  #     # Notify Slack
-  #     - msg="$$(python3 -c "import json,sys;print(json.dumps(sys.argv[1]))" "$$msg")"
-  #     - 'curl -s -XPOST
-  #         -d "{\"channel\": \"#tradingcore-notify\", \"icon_emoji\": \":robot:\", \"text\": $$msg, \"username\": \"nagbot\" }"
-  #         "$$SLACK_HOOK_URL"'
-  #     # Make Github PR comment
-  #     - commentfile="$$(mktemp)"
-  #     - (
-  #         echo "system-tests failed." ;
-  #         echo ;
-  #         echo "\`\`\`" ;
-  #         grep -A1000 "=== Test summary ===" "$$logfile" || echo "No test summary found" ;
-  #         echo "\`\`\`"
-  #       ) >"$$commentfile"
-  #     - body="$$(python3 -c "import json,sys;print(json.dumps(sys.argv[1]))" "$$(cat "$$commentfile")")"
-  #     - 'curl -s -XPOST
-  #         -H "Accept: application/vnd.github.v3+json"
-  #         -H "Authorization: token $$GITHUB_API_TOKEN"
-  #         -d "{\"body\": $$body}"
-  #         "https://api.github.com/repos/vegaprotocol/vega/issues/$$DRONE_PULL_REQUEST/comments"'
-  #     - exit "$$exitcode"
-  #   depends_on:
-  #     - test-PR
-  #   when:
-  #     event:
-  #       - pull_request
+  - name: systemtests-PR
+    image: docker.pkg.github.com/vegaprotocol/system-tests/system-tests:latest
+    pull: always
+    environment:
+      GITHUB_API_TOKEN:
+        from_secret: GITHUB_API_TOKEN
+      SLACK_HOOK_URL:
+        from_secret: SLACK_HOOK_URL
+    commands:
+      # https://github.com/vegaprotocol/system-tests/blob/master/systemtests.sh
+      - codefile="$$(mktemp)" ; logfile="$$(mktemp)"
+      - ln -fs cmd/vega/vega-linux-amd64 cmd/vega/vega
+      - (
+          /usr/local/bin/systemtests.sh -v all ;
+          echo "$$?" >"$$codefile"
+        ) 2>&1 | tee "$$logfile"
+      - test "$$(cat "$$codefile")" = 0 && exit 0
+      # system-tests failed
+      - msgprefix="system-tests failed for PR#$$DRONE_PULL_REQUEST (\`$$DRONE_SOURCE_BRANCH\` -> \`$$DRONE_TARGET_BRANCH\`)"
+      # Failure is fatal only while attempting to merge to master.
+      - if test "$$DRONE_TARGET_BRANCH" = master ; then
+          exitcode=1 ;
+          msg="$$msgprefix *pipeline failed* :cry:" ;
+        else
+          exitcode=0 ;
+          msg="$$msgprefix (pipeline continues)" ;
+        fi
+      # Notify Slack
+      - msg="$$(python3 -c "import json,sys;print(json.dumps(sys.argv[1]))" "$$msg")"
+      - 'curl -s -XPOST
+          -d "{\"channel\": \"#tradingcore-notify\", \"icon_emoji\": \":robot:\", \"text\": $$msg, \"username\": \"nagbot\" }"
+          "$$SLACK_HOOK_URL"'
+      # Make Github PR comment
+      - commentfile="$$(mktemp)"
+      - (
+          echo "system-tests failed." ;
+          echo ;
+          echo "\`\`\`" ;
+          grep -A1000 "=== Test summary ===" "$$logfile" || echo "No test summary found" ;
+          echo "\`\`\`"
+        ) >"$$commentfile"
+      - body="$$(python3 -c "import json,sys;print(json.dumps(sys.argv[1]))" "$$(cat "$$commentfile")")"
+      - 'curl -s -XPOST
+          -H "Accept: application/vnd.github.v3+json"
+          -H "Authorization: token $$GITHUB_API_TOKEN"
+          -d "{\"body\": $$body}"
+          "https://api.github.com/repos/vegaprotocol/vega/issues/$$DRONE_PULL_REQUEST/comments"'
+      - exit "$$exitcode"
+    depends_on:
+      - test-PR
+    when:
+      event:
+        - pull_request
 
   # ====== Pipeline for main branches (master, develop) and tags ======
 
@@ -295,13 +294,9 @@ steps:
       - unset GITHUB_DEPLOY_SSH_PRIVATE_KEY
       - ./script/build.sh -T
     depends_on:
-      - test-PR
+      - build-branch
     when:
-      event: pull_request
-    # depends_on:
-    #   - build-branch
-    # when:
-    #   event: tag
+      event: tag
 
   # http://plugins.drone.io/drone-plugins/drone-github-release/
   - name: publish_artefacts
