Condense drone steps

diff --git a/.drone.yml b/.drone.yml
--- a/.drone.yml
+++ b/.drone.yml
@@ -36,43 +36,45 @@ steps:
           echo "Need env var GITLAB_DEPLOY_SSH_KNOWN_HOSTS to have one or more host keys" ; exit 1 ; fi
       - echo "$${GITLAB_DEPLOY_SSH_PRIVATE_KEY}" >~/.ssh/id_rsa ; chmod 0600 ~/.ssh/id_rsa
       - echo "$${GITLAB_DEPLOY_SSH_KNOWN_HOSTS}" >~/.ssh/known_hosts ; chmod 0644 ~/.ssh/known_hosts
+      - unset GITLAB_DEPLOY_SSH_KNOWN_HOSTS GITLAB_DEPLOY_SSH_PRIVATE_KEY
       - env |sort
       - make deps
       - make install
     depends_on: []
 
-  - name: test
+  # Lightweight tests to be run on all branches.
+  - name: test_light
     image: registry.gitlab.com/vega-protocol/devops-infra/cipipeline:1.11.13
     volumes:
       - name: gopkg
         path: /go/pkg
+    environment:
+      GITLAB_API_TOKEN:
+        from_secret: GITLAB_API_TOKEN
     commands:
       - make test
+      - make coveragehtml
+      # More small checks. Run all, instead of exitng after first failure.
+      - code=0
+      - make print_check || code=1
+      - make rest_check || code=1
+      - make proto_check || code=1
+      - make gqlgen_check || code=1
+      - bash script/diff_graphqlschema.sh || code=1  # requires GITLAB_API_TOKEN
+      - make lint || true  # Ignore lint failure for now (see #196)
+      - exit "$code"
     depends_on:
       - build
 
-  - name: race
+  # Heavyweight tests to be run on main branches only.
+  - name: test_heavy
     image: registry.gitlab.com/vega-protocol/devops-infra/cipipeline:1.11.13
     volumes:
       - name: gopkg
         path: /go/pkg
     commands:
+      - make vet
       - make race
-    depends_on:
-      - build
-    when:
-      branch:
-        - master
-        - develop
-        - release/*
-        - 491-implement-drone-ci-config
-
-  - name: msan
-    image: registry.gitlab.com/vega-protocol/devops-infra/cipipeline:1.11.13
-    volumes:
-      - name: gopkg
-        path: /go/pkg
-    commands:
       - make msan
     depends_on:
       - build
@@ -81,66 +83,7 @@ steps:
         - master
         - develop
         - release/*
-        - 491-implement-drone-ci-config
-
-  - name: coverage
-    image: registry.gitlab.com/vega-protocol/devops-infra/cipipeline:1.11.13
-    volumes:
-      - name: gopkg
-        path: /go/pkg
-    commands:
-      - make coveragehtml
-    depends_on:
-      - build
-    when:
-      branch:
-        - master
-        - develop
-        - release/*
-        - 491-implement-drone-ci-config
-
-  - name: lint
-    image: registry.gitlab.com/vega-protocol/devops-infra/cipipeline:1.11.13
-    volumes:
-      - name: gopkg
-        path: /go/pkg
-    commands:
-      - make print_check || exit 1
-      - export PATH="$${PATH}:/go/bin"
-      - make lint || true  # Ignore lint failure for now (see #196)
-    depends_on:
-      - build
-
-  - name: autogen_checks
-    image: registry.gitlab.com/vega-protocol/devops-infra/cipipeline:1.11.13
-    volumes:
-      - name: gopkg
-        path: /go/pkg
-    commands:
-      - code=0
-      - make rest_check || code=1
-      - make proto_check || code=1
-      - make gqlgen_check || code=1
-      - bash script/diff_graphqlschema.sh || code=1
-      - exit "$code"
-    depends_on:
-      - build
-
-  - name: vet
-    image: registry.gitlab.com/vega-protocol/devops-infra/cipipeline:1.11.13
-    volumes:
-      - name: gopkg
-        path: /go/pkg
-    commands:
-      - make vet
-    depends_on:
-      - build
-    when:
-      branch:
-        - master
-        - develop
-        - release/*
-        - 491-implement-drone-ci-config
+        - 491-implement-drone-ci-config  # TBD: remove
 
   - name: push_to_devnet
     image: registry.gitlab.com/vega-protocol/devops-infra/cipipeline:1.11.13
@@ -150,20 +93,15 @@ steps:
     commands:
       - ./script/deploy.sh devnet vega "/go/bin/vega:/home/vega/current/:0755"
       # Nasty auth hack. Single quotes to avoid yaml k:v pair.
-      - 'for u in $VEGANET_USERS ; do
+      - 'for u in $$VEGANET_USERS ; do
           /go/bin/vegaccount -addr geo.d.vega.xyz:3002 -traderid "$$u" ;
           curl -s -XPOST -H "Content-type: application/json" -H "Authorization: Bearer $$VEGA_AUTH_MASTERTOKEN"
             -d "{\"id\": \"$$u\", \"password\": \"123\"}" https://auth.d.vega.xyz 1>/dev/null ;
           echo ;
         done'
     depends_on:
-      - test
-      - race
-      - msan
-      - coverage
-      - lint
-      - autogen_checks
-      - vet
+      - test_light
+      - test_heavy
     when:
       branch:
         - develop
@@ -185,19 +123,13 @@ steps:
       - docker push "registry.gitlab.com/vega-protocol/trading-core:$$imgtag" || exit 0
       - for app in $$apps ; do rm -f "./$app"; done
     depends_on:
-      - test
-      - race
-      - msan
-      - coverage
-      - lint
-      - autogen_checks
-      - vet
+      - test_light
+      - test_heavy
     when:
       branch:
         - master
         - develop
-        - 491-implement-drone-ci-config
-
+        - 491-implement-drone-ci-config  # TBD: remove
 
 volumes:
   - name: gopkg
