Ignore docker fails in pipeline

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -118,12 +118,12 @@ push_to_devnet:
         "${BIN_DIR}/vegastream:/home/vega/current/:0755"
     # Nasty auth hack. Single quotes to avoid yaml k:v pair.
     - 'for u in $VEGANET_USERS ; do
-            echo -e "\n== $u ==" ;
-            ${BIN_DIR}/vegaccount -addr geo.d.vega.xyz:3002 -traderid "$u" ;
-            curl -s -XPOST -H "Content-type: application/json" -H "Authorization: Bearer $VEGA_AUTH_MASTERTOKEN"
-                -d "{\"id\": \"$u\", \"password\": \"123\"}" https://auth.d.vega.xyz ;
-            echo ;
-        done'
+        echo -e "\n== $u ==" ;
+        ${BIN_DIR}/vegaccount -addr geo.d.vega.xyz:3002 -traderid "$u" ;
+        curl -s -XPOST -H "Content-type: application/json" -H "Authorization: Bearer $VEGA_AUTH_MASTERTOKEN"
+          -d "{\"id\": \"$u\", \"password\": \"123\"}" https://auth.d.vega.xyz ;
+        echo ;
+      done'
   only:
     - /^develop$/  # VERY IMPORTANT: Only the develop branch should be deployed to devnet.
 
@@ -133,15 +133,15 @@ publish-docker:
     - docker:dind
   stage: deploy
   script:
-    - for app in dummyriskmodel vega vegabench vegaccount vegastream ; do
-    - f="${BIN_DIR}/$app"
-    # single quotes to avoid the colon making a yaml key:value pair.
-    - 'if ! test -f "$f" ; then echo "Failed to find: $f" ; exit 1 ; fi'
-    - cp -a "$f" . || exit 1
-    - done
-    - docker login -u gitlab-ci-token -p "${CI_JOB_TOKEN}" registry.gitlab.com || exit 1
-    - docker build -t "registry.gitlab.com/vega-protocol/trading-core:${CI_COMMIT_REF_SLUG}" -f Dockerfile.quick . || exit 1
-    - docker push "registry.gitlab.com/vega-protocol/trading-core:${CI_COMMIT_REF_SLUG}" || exit 1
+    - 'for app in dummyriskmodel vega vegabench vegaccount vegastream ; do
+        f="${BIN_DIR}/$app" ;
+        if ! test -f "$f" ; then echo "Failed to find: $f" ; exit 1 ; fi ;
+        cp -a "$f" . || exit 1 ;
+      done'
+    # Ignore docker fails (devops-infra#26)
+    - docker login -u gitlab-ci-token -p "${CI_JOB_TOKEN}" registry.gitlab.com || exit 0
+    - docker build -t "registry.gitlab.com/vega-protocol/trading-core:${CI_COMMIT_REF_SLUG}" -f Dockerfile.quick . || exit 0
+    - docker push "registry.gitlab.com/vega-protocol/trading-core:${CI_COMMIT_REF_SLUG}" || exit 0
     - for app in vega vegabench ; do rm -f "./$app"; done
   only:
-    - /^(master$|develop$|release/|v[0-9])/
+    - /^(master$|develop$|release/v[0-9])/
